#!/usr/bin/env python3
import argparse
import os
import string
import sys
filepath = os.path.realpath(__file__)
filedir = os.path.dirname(filepath)
parentdir = os.path.dirname(filedir)
xmtoolspath = os.path.join(parentdir, 'xltools')
sys.path.insert(1, xmtoolspath)
import xltools as xl


def _check_positive(value):
    ivalue = int(value)
    if ivalue <= 0:
        raise argparse.ArgumentTypeError(
            "%s is not a positive integer" % value)
    return ivalue


def _parse():
    parser = argparse.ArgumentParser(
        description='read column from an xl* spreadsheet.')
    parser.add_argument('filename', metavar='file',
                        help='file name, e.g. file.xlsx')
    parser.add_argument('sheetname', metavar='sheet',
                        help='sheet name, e.g. ΦΥΛΛΟ_1')
    parser.add_argument('columns', metavar='column', nargs='+',
                        choices=string.ascii_uppercase,
                        help='column letter (A-Z), e.g. A C')
    parser.add_argument('--rowoffset', '-r', type=_check_positive,
                        default=1, help='row to start from, e.g. 3')
    return parser.parse_args()


def _main():
    print(*[','.join(map(lambda str_: f'"{str_}"', lst))
            for lst in xl.read_rows(**vars(_parse()))],
          sep='\n')


if __name__ == '__main__':
    _main()
