#!/usr/bin/env python3
import sys
import logging

from diavlos.src.service import service_logger
from diavlos.src.service import Service

stdout_hdl = logging.StreamHandler(sys.stdout)
stdout_hdl.setLevel(logging.DEBUG)
service_logger.addHandler(stdout_hdl)
service_logger.setLevel(logging.DEBUG)


def main():
    Service().move_all_pages_in_category_to_namespace()


if __name__ == '__main__':
    main()
