#!/usr/bin/env python3
import argparse

from services.src.organization import Organization

COMMANDS = {}
for attr_name in dir(Organization):
    attr_obj = getattr(Organization, attr_name)
    if not attr_name.startswith('_') and callable(attr_obj) and hasattr(
            attr_obj, 'is_cli_command'):
        COMMANDS[attr_name] = attr_obj

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    group = parser.add_mutually_exclusive_group()
    for name in COMMANDS:
        group.add_argument(
            f"--{name.replace('_', '-')}", action='store_true')
    args = parser.parse_args()
    for name, command in COMMANDS.items():
        if getattr(args, name):
            command = getattr(Organization(), name)
            command()
            break
